# Generated by Django 3.2.8 on 2022-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('tech', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('photo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'resumesInfo',
            },
        ),
    ]
